In [8]:
import numpy as np # import the numpy package under the name np
np.__version__ #print the numpy version and the configuration
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2,AVX512F,AVX512CD,AVX512_SKX,AVX512_CLX

In [22]:
arr = np.zeros(10) # create a null vector of size 10
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
arr.size #find the memory size of any array

10

In [15]:
np.info(np.subtract) #to get the documentation of numpy from command line.

subtract(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Subtract arguments, element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be subtracted from each other.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is c

In [24]:
arr = np.arange(10,49)

In [25]:
arr = arr[::-1]
arr

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [30]:
result = np.arange(1, 10)
result.resize(3,3)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
#10: Find indices of non-zero element from [1,2,0,0,4,0]
result = np.nonzero(np.array([1,2,0,0,4,0]))
print(result)

(array([0, 1, 4], dtype=int64),)


In [34]:
#11: Create a 3x3 identity matrix
ID = np.identity(3)
print(ID)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
randArr = np.random.random(27)
randArr.resize(3,3,3)
randArr

array([[[0.19523744, 0.19313022, 0.96461309],
        [0.1387672 , 0.62255199, 0.60209252],
        [0.7090142 , 0.76837965, 0.962361  ]],

       [[0.47407339, 0.17607558, 0.79033097],
        [0.53398293, 0.72454681, 0.32185494],
        [0.58551337, 0.39874364, 0.50070671]],

       [[0.48380289, 0.80332683, 0.0370211 ],
        [0.85300451, 0.33732074, 0.07126299],
        [0.13275618, 0.01094079, 0.95877932]]])

In [37]:
tenXten = np.random.random(100)
tenXten.resize(10,10)
maxVal = np.max(tenXten)
minVal = np.min(tenXten)
print(f"{maxVal} & {minVal}")

0.9919926499158381 & 0.00042591007072156906


In [38]:
randomVec = np.random.random(30)
np.mean(randomVec)

0.5313830879777647

In [ ]:
np.array([1:-1, 1:-1])